### ISSUE TITLE
Don;'t delete duplicates

### ISSUE THREAD

**Issue by elgodox** [mtalcott/google-photos-deduper#47] opened 2024-05-23 19:00 UTC
When I want to delete duplicate photos it opens a new tab and gets stuck there, does not continue, and does not delete duplicates. why?
![image](https://github.com/mtalcott/google-photos-deduper/assets/57495341/9886ff93-5fd4-417d-8bbb-a08affdd8e82)

**Comment by matthewknill** [comment] 2024-05-26 23:17
Yeah for me it loads the images but it doesn't press the button and just fails

**Comment by brianhughesspe** [comment] 2024-05-28 22:25
This is a dupe of [https://github.com/mtalcott/google-photos-deduper/issues/40](https://github.com/mtalcott/google-photos-deduper/issues/40) which it doesn't seem like has been fixed yet.

**Comment by mtalcott** [comment] 2024-05-29 05:41
Closing as dupe of #40

**Closed as completed by mtalcott** 2024-05-29 05:41 UTC
